version: "3.8"
services:
  code-server-jordancodes:
    build: .
    volumes:
       - /tools/visual-studio/config:/root/.config/code-server
       - /tools/visual-studio/project:/root/.local/share/code-server
       - /tools/visual-studio/certbot:/etc/letsencrypt
    ports:
      - 8340:8443
    restart: unless-stopped